=== megu-hub/Guipuzcoa-Desktop/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/TextFile1" elementFormDefault="qualified" targetNamespace="http://tempuri.org/TextFile1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
			<xs:attribute name="provincia" type="xs:string" use="required" />
			<xs:attribute name="pais" type="xs:string" use="required" />
			<xs:attribute name="region" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tipo" />
				<xs:element ref="medioTransporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fechaInicio" />
				<xs:element minOccurs="0" maxOccurs="1" ref="horaInicio" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="personasAdecuadas" />
				<xs:element ref="lugarInicio" />
				<xs:element ref="direccionInicio" />
				<xs:element ref="coordenadasInicio" />
				<xs:element ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
				<xs:element ref="puntosRuta" />
				<xs:element ref="planimetria" />
				<xs:element ref="altimetria" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="tipo" type="xs:string" />
	<xs:element name="medioTransporte" type="xs:string" />
	<xs:element name="duracion" type="xs:string" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="personasAdecuadas" type="xs:string" />
	<xs:element name="lugarInicio" type="xs:string" />
	<xs:element name="direccionInicio" type="xs:string" />
	<xs:element name="recomendacion" type="xs:string" />
	<xs:element name="planimetria" type="xs:string" />
	<xs:element name="altimetria" type="xs:string" />
	<xs:element name="fechaInicio">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute default="true" name="opcional">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="true" />
								<xs:enumeration value="false" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="horaInicio">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute default="true" name="opcional">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="true" />
								<xs:enumeration value="false" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadasInicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencia" />
				<xs:element ref="referencia" />
				<xs:element ref="referencia" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hito" />
				<xs:element ref="hito" />
				<xs:element ref="hito" />
				<xs:element ref="hito" />
				<xs:element ref="hito" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="descripcion" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distanciaDesdeAnterior" />
				<xs:element ref="galeriaFotos" />
				<xs:element minOccurs="0" maxOccurs="1" ref="galeriaVideos" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distanciaDesdeAnterior">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidades" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="km" />
								<xs:enumeration value="m" />
								<xs:enumeration value="mi" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="video" />
				<xs:element minOccurs="0" maxOccurs="1" ref="video" />
				<xs:element minOccurs="0" maxOccurs="1" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntosRuta">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:attribute name="longitud" type="xs:string" use="required" />
			<xs:attribute name="latitud" type="xs:string" use="required" />
			<xs:attribute name="altitud" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== megu-hub/Guipuzcoa-Desktop/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas provincia="Gipuzkoa" pais="España" region="País Vasco" xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
  <ruta id="R001">
    <nombre>Ruta de la Costa Vasca: De Getaria a Zumaia</nombre>
    <tipo>Paisajística</tipo>
    <medioTransporte>A pie</medioTransporte>
    <fechaInicio opcional="true">2025-06-15</fechaInicio>
    <horaInicio opcional="true">09:00</horaInicio>
    <duracion>1 día</duracion>
    <agencia>Geoparke Euskal Kostaldea</agencia>
    <descripcion>Recorrido a pie por los acantilados y playas de la costa guipuzcoana, desde Getaria hasta Zumaia, atravesando el Geoparque Mundial UNESCO del Flysch.</descripcion>
    <personasAdecuadas>Personas en buena forma física; no recomendada para tercera edad ni niños menores de 10 años</personasAdecuadas>
    <lugarInicio>Puerto de Getaria</lugarInicio>
    <direccionInicio>Calle Nagusia 1, Getaria</direccionInicio>
    <coordenadasInicio>
      <longitud>-2.2028</longitud>
      <latitud>43.3001</latitud>
      <altitud>5</altitud>
    </coordenadasInicio>
    <referencias>
      <referencia id="R001-ref1">https://www.turismogipuzkoa.eus/es/costa-vasca</referencia>
      <referencia id="R001-ref2">https://es.wikipedia.org/wiki/Flysch_de_Zumaia</referencia>
      <referencia id="R001-ref3">https://www.geoparkevasco.eus/es/rutas/costa</referencia>
      <referencia id="R001-ref4">https://www.wikiloc.com/rutas-senderismo/getaria-zumaia-costa</referencia>
    </referencias>
    <recomendacion>9</recomendacion>

    <hitos>
      <hito id="H001-01">
        <nombre>Puerto pesquero de Getaria</nombre>
        <descripcion>Punto de partida. Puerto pintoresco con flota pesquera activa. Frente a él se alza la isla de San Antón (el Ratón de Getaria). Cuna de Juan Sebastián Elcano y Cristóbal Balenciaga.</descripcion>
        <coordenadas>
          <longitud>-2.2028</longitud>
          <latitud>43.3001</latitud>
          <altitud>5</altitud>
        </coordenadas>
        <distanciaDesdeAnterior unidades="km">0</distanciaDesdeAnterior>
        <galeriaFotos>
          <foto alt="Vista panorámica del puerto de Getaria con barcos pesqueros">../multimedia/R001/H001-01_puerto_panoramica.jpg</foto>
          <foto alt="Isla de San Antón (el Ratón) vista desde el puerto de Getaria">../multimedia/R001/H001-01_isla_raton.jpg</foto>
        </galeriaFotos>
        <galeriaVideos>
          <video alt="Vídeo del amanecer en el puerto de Getaria con actividad pesquera">../multimedia/R001/H001-01_puerto_amanecer.mp4</video>
        </galeriaVideos>
      </hito>

      <hito id="H001-02">
        <nombre>Museo Cristóbal Balenciaga</nombre>
        <descripcion>Museo dedicado al modisto nacido en Getaria en 1895. El edificio combina palacio histórico y volumen de cristal contemporáneo. Más de 1.200 piezas originales del diseñador.</descripcion>
        <coordenadas>
          <longitud>-2.2041</longitud>
          <latitud>43.3010</latitud>
          <altitud>12</altitud>
        </coordenadas>
        <distanciaDesdeAnterior unidades="m">250</distanciaDesdeAnterior>
        <galeriaFotos>
          <foto alt="Fachada exterior del Museo Balenciaga con su volumen de cristal contemporáneo">../multimedia/R001/H001-02_museo_fachada.jpg</foto>
        </galeriaFotos>
        <galeriaVideos>
          <video alt="Vídeo de visita virtual a las salas del Museo Cristóbal Balenciaga">../multimedia/R001/H001-02_museo_visita_virtual.mp4</video>
        </galeriaVideos>
      </hito>

      <hito id="H001-03">
        <nombre>Playa de Malkorbe</nombre>
        <descripcion>Playa virgen de acceso difícil entre Getaria y Zumaia. Arenas doradas rodeadas de acantilados. Zona de especial protección medioambiental con avistamiento de aves marinas.</descripcion>
        <coordenadas>
          <longitud>-2.2280</longitud>
          <latitud>43.2967</latitud>
          <altitud>3</altitud>
        </coordenadas>
        <distanciaDesdeAnterior unidades="km">2.8</distanciaDesdeAnterior>
        <galeriaFotos>
          <foto alt="Vista aérea de la playa virgen de Malkorbe rodeada de acantilados">../multimedia/R001/H001-03_malkorbe_aerea.jpg</foto>
          <foto alt="Acantilados que flanquean la playa de Malkorbe en la costa vasca">../multimedia/R001/H001-03_malkorbe_acantilados.jpg</foto>
        </galeriaFotos>
      </hito>

      <hito id="H001-04">
        <nombre>Acantilados del Flysch de Zumaia</nombre>
        <descripcion>Acantilados con sección estratigráfica continua de 50 millones de años. Geoparque Mundial UNESCO desde 2015. Sus estratos muestran el límite K-Pg relacionado con la extinción de los dinosaurios.</descripcion>
        <coordenadas>
          <longitud>-2.2500</longitud>
          <latitud>43.2920</latitud>
          <altitud>80</altitud>
        </coordenadas>
        <distanciaDesdeAnterior unidades="km">2.1</distanciaDesdeAnterior>
        <galeriaFotos>
          <foto alt="Estratos verticales del flysch de Zumaia mostrando millones de años de historia geológica">../multimedia/R001/H001-04_flysch_estratos.jpg</foto>
          <foto alt="Panorámica aérea de los acantilados del Geoparque del Flysch de Zumaia">../multimedia/R001/H001-04_flysch_panoramica.jpg</foto>
        </galeriaFotos>
        <galeriaVideos>
          <video alt="Documental geológico sobre la formación y significado del flysch de Zumaia">../multimedia/R001/H001-04_flysch_documental.mp4</video>
        </galeriaVideos>
      </hito>

      <hito id="H001-05">
        <nombre>Playa de Itzurun</nombre>
        <descripcion>Playa espectacular flanqueada por acantilados de flysch. Escenario de rodaje de Juego de Tronos (Rocadragón). Permite apreciar de cerca las formaciones rocosas del Geoparque.</descripcion>
        <coordenadas>
          <longitud>-2.2549</longitud>
          <latitud>43.2887</latitud>
          <altitud>2</altitud>
        </coordenadas>
        <distanciaDesdeAnterior unidades="m">800</distanciaDesdeAnterior>
        <galeriaFotos>
          <foto alt="Playa de Itzurun con los impresionantes acantilados de flysch al fondo">../multimedia/R001/H001-05_itzurun_playa.jpg</foto>
          <foto alt="Atardecer sobre la playa de Itzurun y los acantilados de Zumaia">../multimedia/R001/H001-05_itzurun_atardecer.jpg</foto>
        </galeriaFotos>
        <galeriaVideos>
          <video alt="Vídeo de dron sobrevolando la playa de Itzurun y los acantilados de flysch">../multimedia/R001/H001-05_itzurun_drone.mp4</video>
        </galeriaVideos>
      </hito>

      <hito id="H001-06">
        <nombre>Centro de Interpretación Algorri (Zumaia)</nombre>
        <descripcion>Centro geológico del Geoparque en el casco histórico de Zumaia. Exposiciones interactivas sobre el flysch. Punto final de la ruta, en una antigua estructura portuaria rehabilitada.</descripcion>
        <coordenadas>
          <longitud>-2.2561</longitud>
          <latitud>43.2895</latitud>
          <altitud>10</altitud>
        </coordenadas>
        <distanciaDesdeAnterior unidades="m">500</distanciaDesdeAnterior>
        <galeriaFotos>
          <foto alt="Exterior del Centro de Interpretación Algorri junto al puerto de Zumaia">../multimedia/R001/H001-06_algorri_exterior.jpg</foto>
          <foto alt="Sala de exposición interactiva del Centro Algorri sobre geología del flysch">../multimedia/R001/H001-06_algorri_interior.jpg</foto>
        </galeriaFotos>
      </hito>
    </hitos>

    <puntosRuta>
      <punto longitud="-2.2028" latitud="43.3001" altitud="5"/>
      <punto longitud="-2.2035" latitud="43.2998" altitud="6"/>
      <punto longitud="-2.2041" latitud="43.3010" altitud="12"/>
      <punto longitud="-2.2055" latitud="43.3005" altitud="15"/>
      <punto longitud="-2.2080" latitud="43.2995" altitud="22"/>
      <punto longitud="-2.2110" latitud="43.2985" altitud="35"/>
      <punto longitud="-2.2145" latitud="43.2975" altitud="48"/>
      <punto longitud="-2.2175" latitud="43.2970" altitud="30"/>
      <punto longitud="-2.2210" latitud="43.2965" altitud="10"/>
      <punto longitud="-2.2245" latitud="43.2960" altitud="5"/>
      <punto longitud="-2.2280" latitud="43.2967" altitud="3"/>
      <punto longitud="-2.2310" latitud="43.2958" altitud="20"/>
      <punto longitud="-2.2340" latitud="43.2945" altitud="45"/>
      <punto longitud="-2.2370" latitud="43.2935" altitud="65"/>
      <punto longitud="-2.2400" latitud="43.2928" altitud="78"/>
      <punto longitud="-2.2430" latitud="43.2922" altitud="80"/>
      <punto longitud="-2.2465" latitud="43.2918" altitud="75"/>
      <punto longitud="-2.2500" latitud="43.2920" altitud="80"/>
      <punto longitud="-2.2510" latitud="43.2912" altitud="60"/>
      <punto longitud="-2.2520" latitud="43.2900" altitud="35"/>
      <punto longitud="-2.2535" latitud="43.2892" altitud="12"/>
      <punto longitud="-2.2549" latitud="43.2887" altitud="2"/>
      <punto longitud="-2.2552" latitud="43.2889" altitud="5"/>
      <punto longitud="-2.2555" latitud="43.2891" altitud="8"/>
      <punto longitud="-2.2558" latitud="43.2893" altitud="9"/>
      <punto longitud="-2.2561" latitud="43.2895" altitud="10"/>
    </puntosRuta>

    <planimetria>R001_planimetria.kml</planimetria>
    <altimetria>R001_altimetria.svg</altimetria>
  </ruta>


  <!-- ==================== RUTA 2 ==================== -->
  <ruta id="R002">
    <nombre>Ruta de Pintxos y Monumentos por la Parte Vieja de Donostia</nombre>
    <tipo>Mixta tapas y monumentos</tipo>
    <medioTransporte>A pie</medioTransporte>
    <fechaInicio opcional="true">2025-07-20</fechaInicio>
    <horaInicio opcional="true">11:00</horaInicio>
    <duracion>4 horas</duracion>
    <agencia>Donostia San Sebastián Turismoa</agencia>
